FROM python:3.13.2  
WORKDIR /app  
COPY . /app  

# Install system dependencies  
RUN apt-get update && apt-get install -y libpcap-dev  

# Install Python dependencies  
RUN pip install --upgrade pip  
RUN pip install --no-cache-dir -r requirements.txt  

CMD ["python", "/app/fingerprinting.py"]
